default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*\\.enc\\.json$"  # Ignore SOPS-encrypted JSON files
      - id: end-of-file-fixer
        exclude: ".*\\.enc\\.json$"  # Ignore SOPS-encrypted JSON files
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
