name: Aggregate content

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: scripts/ingest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingesters
        run: |
          python scripts/ingest/ingest_docs.py
          python scripts/ingest/ingest_releases.py
          python scripts/ingest/ingest_events.py

      - name: Commit changes
        run: |
          git config user.name "kubermates-bot"
          git config user.email "bot@kubermates.org"
          git add content/ scripts/ingest/state.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(ingest): update aggregated content"
            git push
          else
            echo "No changes"
