name: Aggregate content

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: scripts/ingest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingesters
        run: |
          python scripts/ingest/ingest_docs.py
          python scripts/ingest/ingest_releases.py
          python scripts/ingest/ingest_events.py

      - name: Commit to a temp branch
        run: |
          set -euo pipefail
          git config user.name "kubermates-bot"
          git config user.email "bot@kubermates.org"
          git checkout -B bot/ingest-update
          git add content/ scripts/ingest/state.json
          if ! git diff --cached --quiet; then
            git commit -m "chore(ingest): update aggregated content"
            git push --force-with-lease origin HEAD:bot/ingest-update
          else
            echo "No changes"
            exit 0
          fi

      - name: Switch back to main
        run: git checkout main

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: bot/ingest-update
          title: chore ingest update aggregated content
          commit-message: chore ingest update aggregated content
          body: Automated content aggregation
          delete-branch: true
